### PR TITLE
T2 constructor

### PR DESCRIPTION
**Pull request by camelStyleUser**
idk how to merge this

### CODE REVIEW

**Comment by camelStyleUser** [comment]
@RouterXdd should i resolve the conflict in favor of main branch or t2-reconstructor?

**Comment by RouterXdd** [comment]
-_-
This is all strange...
Universal assembler is Unit assembler (Factory T4 and T5 from Erekir), not reconstructor, not factory

**Comment by camelStyleUser** [comment]
i just use sprites that are present in source code:)

**Comment by oleksiy1409liut** [comment]
пж обновите мод бистрее

**Comment by camelStyleUser** [comment]
well works for me so i merge

**Pull request merged**
